### ISSUE TITLE
Type inference: Boolean type, Comparison, Logical and negation operators

### ISSUE THREAD

**Issue by ishikawa** [ishikawa/nico#142]
Type annotation for boolean type: `Bool`

```
fun is_zero(n: Int) -> Bool
```

Comparison operators: Both operands must be the same type. The result type is `Bool`.

- `>` `>=` `<` `<=` `==` `!=` 

Logical operators: Both operands must be a value of the type `Bool`. The result type is `Bool`.

- `&&` `||`

Negation operator: An operand must be a value of the type `Bool`. The result type is `Bool`.

- `!`

## Todo

- [x] Type annotation for boolean type: `Bool`
- [x] Comparison operators: Both operands must be the same type. The result type is `Bool`.
- [x] Logical operators: Both operands must be a value of the type `Bool`. The result type is `Bool`.
- [x] Negation operator: An operand must be a value of the type `Bool`. The result type is `Bool`.

**Comment by ishikawa** [comment]
<img width="305" alt="スクリーンショット 2021-07-07 20 12 39" src="https://user-images.githubusercontent.com/18448/124749974-deeea100-df5f-11eb-8e07-09b45acb343f.png">
