### ISSUE TITLE
[a, r, r, a, y]

### ISSUE THREAD

**Issue by ishikawa** [ishikawa/nico#39]
I would like to add `array`s to the language.

- An array is a sequence of values arranged in a memory area.
- Accessing by index is *O(1)*.
  - ~~However, I don't implement *index operator* in this time.~~
  - ~~To implement it, I have to consider `Optional` type in the language.~~
  - Index operator yield `trap` if the index is overflow. 
  - Note about optional type: I don't like `Some(x)` and `None` everywhere.
    - Can't I write simply `nil` and `<something>`? But I can't imagine how type inferencer work.
- Immutable. Call by Reference
- Array slices can be created without copying
- Pattern matching: per element and rest pattern `...`

```ruby
# i32[] -> i32
fun max(numbers)
    case numbers
    when []
        # Because we don't have `Optional` type yet, returns `-1` for empty array :-(
        -1
    when [x]
        x
    when [n, m] if n > m
        n
    when [_, m]
        m
    when [n, ...rest]
        max(n, rest)
    end
end

max([11, 53, 74, 41, 24, 10, 59, 63, 98, 1]) # => 98
```

## Todo

- [x] Parser #41
- [x] Type inference #42
- [x] Allocate stack in module's `memory` and add stack pointer #43
- [x] Allocate array in stack. #43
- [x] Add index operator #44
- [x] `case` without `else` #46
- [x] Pattern match: `[x]`, `[x, y]` #47
- [x] Rest pattern #50
- [x] ignore pattern `_` and `...` #53
- [x] unary minus #49

**Comment by ishikawa** [comment]
Documentation about memory layout https://github.com/ishikawa/nico/pull/43/commits/a0094f31fa904d3ddc2afa3801cbfc979faaddd8
